from .nodes.lora_remap_anima import (
    NODE_CLASS_MAPPINGS as _LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _LORA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.model_merge_anima import (
    NODE_CLASS_MAPPINGS as _MERGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _MERGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.lora_remap_extended_anima import (
    NODE_CLASS_MAPPINGS as _LORA_EXT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _LORA_EXT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.model_merge_extended_anima import (
    NODE_CLASS_MAPPINGS as _MERGE_EXT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _MERGE_EXT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.anima_random_lora_loader import (
    NODE_CLASS_MAPPINGS as _RANDOM_LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _RANDOM_LORA_NODE_DISPLAY_NAME_MAPPINGS,
)
# Imported for its side effect: registers the /anima_remap/* routes used by the
# LoRA autocomplete in the tag loader text box (web/anima_lora_autocomplete.js).
from .nodes import lora_autocomplete_api  # noqa: F401
from .nodes.anima_filtered_random_lora_loader import (
    NODE_CLASS_MAPPINGS as _FILTERED_RANDOM_LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _FILTERED_RANDOM_LORA_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **_LORA_NODE_CLASS_MAPPINGS,
    **_MERGE_NODE_CLASS_MAPPINGS,
    **_LORA_EXT_NODE_CLASS_MAPPINGS,
    **_MERGE_EXT_NODE_CLASS_MAPPINGS,
    **_RANDOM_LORA_NODE_CLASS_MAPPINGS,
    **_FILTERED_RANDOM_LORA_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **_LORA_NODE_DISPLAY_NAME_MAPPINGS,
    **_MERGE_NODE_DISPLAY_NAME_MAPPINGS,
    **_LORA_EXT_NODE_DISPLAY_NAME_MAPPINGS,
    **_MERGE_EXT_NODE_DISPLAY_NAME_MAPPINGS,
    **_RANDOM_LORA_NODE_DISPLAY_NAME_MAPPINGS,
    **_FILTERED_RANDOM_LORA_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
